name: Flux Kustomize Diff

on: push

jobs:
  diff-flux-kustomizations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: base_branch

      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          path: current_branch

      - id: diff_flux_kustomizations
        uses: felixskaiser/flux-diff-action@fix-action-path
        with:
          src_path: base_branch
          dst_path: current_branch
          output_type: pr_comment
