name: Flux Kustomize Diff

on:
  pull_request:
    branches: [main]

jobs:
  compare_dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3

      - id: diff_flux_kustomizations
        uses: felixskaiser/flux-diff-action@fix-action-path
        with:
          src_path: clusters/production
          dst_path: clusters/staging

      - name: Output
        run: echo '${{ steps.diff_flux_kustomizations.outputs.diff }}'

  pr_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: base_branch

      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          path: current_branch

      - id: diff_flux_kustomizations
        uses: felixskaiser/flux-diff-action@fix-action-path
        with:
          src_path: base_branch
          dst_path: current_branch
          output_type: pr_comment

  job_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: base_branch

      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          path: current_branch

      - id: diff_flux_kustomizations
        uses: felixskaiser/flux-diff-action@fix-action-path
        with:
          src_path: base_branch
          dst_path: current_branch
          output_type: job_summary
