name: Flux Kustomize Diff

on: push

jobs:
  diff-flux-kustomizations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main_branch

      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          path: current_branch

      - id: diff_flux_kustomizations
        uses: felixskaiser/flux-diff-action@fix-action-path
        with:
          src_path: main_branch
          dst_path: current_branch
          output_format: markdown

      # Use single quotes ('') to prevent command substitution because of backticks (```)
      - name: Add to job summary
        run: printf "%s" ${{ steps.diff_flux_kustomizations.outputs.diff }} >> "$GITHUB_STEP_SUMMARY"
